package index

import (
	"context"
	"database/sql"
	"errors"
	"os"
	"path/filepath"
	"strconv"
	"testing"
)

// copyFixture copies a committed index somewhere it may be written to:
// opening one writes, and the fixture must stay what v0.0.1 produced.
func copyFixture(t *testing.T, name string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join("testdata", name))
	if err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(t.TempDir(), "index.db")
	if err := os.WriteFile(path, b, 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

func count(t *testing.T, db *sql.DB, q string) int {
	t.Helper()
	var n int
	if err := db.QueryRow(q).Scan(&n); err != nil {
		t.Fatalf("%s: %v", q, err)
	}
	return n
}

// A real database written by a released binary must open, keep everything it
// arrived with, and need no reset (#66). Generated by v0.0.1, not by this
// code, so a change that does not realise it is destructive fails here.
func TestReleasedIndexOpensIntact(t *testing.T) {
	path := copyFixture(t, "v0.0.1.db")

	db, reset, err := OpenOrReset(path, DriverName)
	if err != nil {
		t.Fatalf("opening v0.0.1's index: %v", err)
	}
	defer db.Close()
	if reset != nil {
		t.Fatalf("v0.0.1's index was reset: %+v", reset)
	}
	s := db.SQL()

	if got := count(t, s, `SELECT COUNT(*) FROM messages`); got != 48 {
		t.Errorf("messages = %d, want the 48 it arrived with", got)
	}
	if got := count(t, s, `SELECT COUNT(*) FROM sessions
		WHERE title LIKE 'Fixture session title %'
		  AND title_key IS NOT NULL AND title_msgs = n_msgs`); got != 3 {
		t.Errorf("%d sessions kept title, title_key and title_msgs, want 3", got)
	}
	if got := count(t, s, `SELECT COUNT(*) FROM chunks`); got != 46 {
		t.Errorf("chunks = %d, want 46", got)
	}
	// The doctor invariants that hold without the model.
	if got := count(t, s, `SELECT ABS((SELECT COUNT(*) FROM chunks_fts) - (SELECT COUNT(*) FROM chunks))`); got != 0 {
		t.Errorf("fts rows minus chunks = %d", got)
	}
	if got := count(t, s, `SELECT COUNT(*) FROM sessions s
		WHERE s.n_msgs <> (SELECT COUNT(*) FROM messages m WHERE m.session_id = s.id)`); got != 0 {
		t.Errorf("%d sessions disagree with their archive", got)
	}

	if v, _ := db.Meta(MetaSchemaVersion); v != strconv.Itoa(SchemaVersion) {
		t.Errorf("schema_version = %q, want %d", v, SchemaVersion)
	}
	if n, err := db.appliedMigrations(); err != nil || n != len(migrations) {
		t.Errorf("migrations applied = %d, %v; want all %d", n, err, len(migrations))
	}
	// And it is usable, not merely openable: the view this build added since.
	count(t, s, `SELECT COUNT(*) FROM tool_calls`)
}

// The archive is the one thing a rebuild cannot recover. A stale index that
// holds one is moved aside whole, never deleted (#64).
func TestStaleIndexWithAnArchiveIsKept(t *testing.T) {
	path := copyFixture(t, "v0.0.1.db")
	raw, err := sql.Open(DriverName, path)
	if err != nil {
		t.Fatal(err)
	}
	if _, err := raw.Exec(`UPDATE meta SET value = '0' WHERE key = 'schema_version'`); err != nil {
		t.Fatal(err)
	}
	raw.Close()

	db, reset, err := OpenOrReset(path, DriverName)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()
	if reset == nil || reset.Kept == "" {
		t.Fatalf("reset = %+v, want the old index kept", reset)
	}
	if got := count(t, db.SQL(), `SELECT COUNT(*) FROM sessions`); got != 0 {
		t.Errorf("the new index has %d sessions, want an empty one", got)
	}

	old, err := sql.Open(DriverName, reset.Kept)
	if err != nil {
		t.Fatal(err)
	}
	defer old.Close()
	if got := count(t, old, `SELECT COUNT(*) FROM messages`); got != 48 {
		t.Errorf("the kept index has %d messages, want 48", got)
	}
}

// An index from a newer spireweb is refused and left exactly as it was: this
// build cannot know what it would be throwing away.
func TestNewerIndexIsRefusedAndUntouched(t *testing.T) {
	path := copyFixture(t, "v0.0.1.db")
	db, err := Open(path, DriverName)
	if err != nil {
		t.Fatal(err)
	}
	if err := db.SetMeta(MetaMigrations, strconv.Itoa(len(migrations)+1)); err != nil {
		t.Fatal(err)
	}
	if err := db.Checkpoint(); err != nil {
		t.Fatal(err)
	}
	db.Close()
	before, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}

	_, reset, err := OpenOrReset(path, DriverName)
	var newer *NewerIndexError
	if !errors.As(err, &newer) {
		t.Fatalf("err = %v, want NewerIndexError", err)
	}
	if reset != nil {
		t.Errorf("a newer index was reset: %+v", reset)
	}

	after, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if string(before) != string(after) {
		t.Error("refusing the index still wrote to it")
	}
	if _, err := os.Stat(path + "-wal"); err == nil {
		if b, _ := os.ReadFile(path + "-wal"); len(b) > 0 {
			t.Errorf("refusing the index left %d bytes of WAL", len(b))
		}
	}
}

// Migrations run in order, once each, and a failure keeps the ones before it.
func TestMigrationsApplyInOrderAndStopAtAFailure(t *testing.T) {
	path := copyFixture(t, "v0.0.1.db")
	var ran []int
	step := func(i int, fail bool) migration {
		return migration{desc: "step " + strconv.Itoa(i), apply: func(tx *sql.Tx) error {
			ran = append(ran, i)
			if fail {
				return errors.New("no")
			}
			_, err := tx.Exec(`ALTER TABLE sessions ADD COLUMN step` + strconv.Itoa(i) + ` TEXT`)
			return err
		}}
	}
	saved := migrations
	t.Cleanup(func() { migrations = saved })

	migrations = append(append([]migration{}, saved...), step(1, false), step(2, true))
	if _, err := Open(path, DriverName); err == nil {
		t.Fatal("a failing migration opened anyway")
	}
	migrations = append(append([]migration{}, saved...), step(1, false), step(2, false))
	db, err := Open(path, DriverName)
	if err != nil {
		t.Fatal(err)
	}
	defer db.Close()

	if want := "[1 2 2]"; fmtInts(ran) != want {
		t.Errorf("ran %v, want %s: the first once, the failed one again", ran, want)
	}
	if n, _ := db.appliedMigrations(); n != len(migrations) {
		t.Errorf("applied = %d, want %d", n, len(migrations))
	}
	if has, _ := db.hasColumn("sessions", "step2"); !has {
		t.Error("the retried migration did not take effect")
	}
}

// A fresh index records every migration as applied: it was created with the
// layout they produce.
func TestFreshIndexNeedsNoMigrations(t *testing.T) {
	db := openTest(t)
	if n, err := db.appliedMigrations(); err != nil || n != len(migrations) {
		t.Errorf("applied = %d, %v; want %d", n, err, len(migrations))
	}
	if _, err := Build(context.Background(), db, BuildOptions{Dirs: []string{writeCorpus(t, map[string][]string{
		"s": {userMsg("hello")},
	})}}); err != nil {
		t.Fatal(err)
	}
}

func fmtInts(xs []int) string {
	s := "["
	for i, x := range xs {
		if i > 0 {
			s += " "
		}
		s += strconv.Itoa(x)
	}
	return s + "]"
}

// An index from a released binary merges as it is: it records no migrations,
// which is what it has.
func TestReleasedIndexMerges(t *testing.T) {
	db := openTest(t)
	p, err := Merge(context.Background(), db, copyFixture(t, "v0.0.1.db"), MergeOptions{})
	if err != nil {
		t.Fatalf("merging v0.0.1's index: %v", err)
	}
	if got := count(t, db.SQL(), `SELECT COUNT(*) FROM messages`); got != 48 {
		t.Errorf("merged %d messages, want 48 (%+v)", got, p)
	}
}
